name: First workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
        - name: Get Code
          uses: actions/checkout@v3
        - name: Build solution
          run: |
            echo "Add folder"
            mkdir testing
            cd testing
            touch somefile.txt
            ls
            pwd
            echo "Test completed"
