name: First workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
        - name: Build soluction
          run: |
            echo "Build project"
            echo "Generate binary"
        - name: Run Tests
          run: echo "Run all tests"
