name: First workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
        - name: Print bye
          run: echo "Bye everyone"
        - name: Print bye
          run: echo "Bye everyone"
